In [ ]:
# Selenium script
options = Options()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
driver = webdriver.Chrome(
service=Service(ChromeDriverManager().install()), options=options
)

# store starting time
begin = time.time()

# FINRA's TRACE Bond Center
driver.get("http://finra-markets.morningstar.com/BondCenter/Results.jsp")

# click agree
WebDriverWait(driver, 10).until(
EC.element_to_be_clickable((By.CSS_SELECTOR, ".button_blue.agree"))
).click()

# click edit search
WebDriverWait(driver, 10).until(
EC.element_to_be_clickable((By.CSS_SELECTOR, "a.qs-ui-btn.blue"))
).click()

# input Issuer Name
WebDriverWait(driver, 10).until(
EC.presence_of_element_located((By.CSS_SELECTOR, "input[id=firscreener-issuer]"))
)
inputElement = driver.find_element(By.ID,"firscreener-issuer")
inputElement.send_keys(company_name)

# input Symbol
WebDriverWait(driver, 10).until(
EC.presence_of_element_located((By.CSS_SELECTOR, "input[id=firscreener-cusip]"))
)
inputElement = driver.find_element(By.ID,"firscreener-cusip")
inputElement.send_keys(company_ticker)

# click advanced search
WebDriverWait(driver, 10).until(
EC.element_to_be_clickable((By.CSS_SELECTOR, "a.ms-display-switcher.hide"))
).click()

# input Coupon Frequency
WebDriverWait(driver, 10).until(
EC.presence_of_element_located((By.CSS_SELECTOR, "select[name=interestFrequency]"))
)
Select(
(driver.find_elements(By.CSS_SELECTOR,"select[name=interestFrequency]"))[0]
).select_by_visible_text(coupon_frequency)

# click show results
WebDriverWait(driver, 10).until(
EC.element_to_be_clickable((By.CSS_SELECTOR, "input.button_blue[type=submit]"))
).click()

# wait for results
WebDriverWait(driver, 10).until(
EC.presence_of_element_located(
(By.CSS_SELECTOR, ".rtq-grid-row.rtq-grid-rzrow .rtq-grid-cell-ctn")
)
)

# create DataFrame from scrape
frames = []
for page in range(1, 11):
bonds = []
WebDriverWait(driver, 10).until(
EC.presence_of_element_located(
(By.CSS_SELECTOR, (f"a.qs-pageutil-btn[value='{str(page)}']"))
)
) # wait for page marker to be on expected page
time.sleep(2)

headers = [
title.text
for title in driver.find_elements(
By.CSS_SELECTOR,".rtq-grid-row.rtq-grid-rzrow .rtq-grid-cell-ctn"
)[1:]
]

tablerows = driver.find_elements(
By.CSS_SELECTOR,"div.rtq-grid-bd > div.rtq-grid-row"
)
for tablerow in tablerows:
tablerowdata = tablerow.find_elements(By.CSS_SELECTOR,"div.rtq-grid-cell")
bond = [item.text for item in tablerowdata[1:]]
bonds.append(bond)

# Convert to DataFrame
df = pd.DataFrame(bonds, columns=headers)

frames.append(df)

try:
driver.find_element(By.CSS_SELECTOR,"a.qs-pageutil-next").click()
except: # noqa E722
break

bond_prices_df = pd.concat(frames)

# store end time
end = time.time()

# total time taken
print(f"Total runtime of the program is {end - begin} seconds")

bond_prices_df

In [ ]:
# Selenium script
options = Options()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()), options=options
)

# store starting time
begin = time.time()

# FINRA's TRACE Bond Center
driver.get("http://finra-markets.morningstar.com/BondCenter/Results.jsp")

# click agree
WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, ".button_blue.agree"))
).click()

# click edit search
WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, "a.qs-ui-btn.blue"))
).click()

# input Issuer Name
WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.CSS_SELECTOR, "input[id=firscreener-issuer]"))
)
inputElement = driver.find_element(By.ID,"firscreener-issuer")
inputElement.send_keys(company_name)

# input Symbol
WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.CSS_SELECTOR, "input[id=firscreener-cusip]"))
)
inputElement = driver.find_element(By.ID,"firscreener-cusip")
inputElement.send_keys(company_ticker)

# click advanced search
WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, "a.ms-display-switcher.hide"))
).click()

# input Coupon Frequency
WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.CSS_SELECTOR, "select[name=interestFrequency]"))
)
Select(
    (driver.find_elements(By.CSS_SELECTOR,"select[name=interestFrequency]"))[0]
).select_by_visible_text(coupon_frequency)

# click show results
WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, "input.button_blue[type=submit]"))
).click()

# wait for results
WebDriverWait(driver, 10).until(
    EC.presence_of_element_located(
        (By.CSS_SELECTOR, ".rtq-grid-row.rtq-grid-rzrow .rtq-grid-cell-ctn")
    )
)

# create DataFrame from scrape
frames = []
for page in range(1, 11):
    bonds = []
    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located(
            (By.CSS_SELECTOR, (f"a.qs-pageutil-btn[value='{str(page)}']"))
        )
    )  # wait for page marker to be on expected page
    time.sleep(2)

    headers = [
        title.text
        for title in driver.find_elements(By.CSS_SELECTOR,
            ".rtq-grid-row.rtq-grid-rzrow .rtq-grid-cell-ctn"
        )[1:]
    ]

    tablerows = driver.find_elements(By.CSS_SELECTOR,
        "div.rtq-grid-bd > div.rtq-grid-row"
    )
    for tablerow in tablerows:
        tablerowdata = tablerow.find_elements(By.CSS_SELECTOR,"div.rtq-grid-cell")
        bond = [item.text for item in tablerowdata[1:]]
        bonds.append(bond)

        # Convert to DataFrame
        df = pd.DataFrame(bonds, columns=headers)

    frames.append(df)

    try:
        driver.find_elements(By.CSS_SELECTOR,"a.qs-pageutil-next").click()
    except:  # noqa E722
        break

bond_prices_df = pd.concat(frames)

# store end time
end = time.time()

# total time taken
print(f"Total runtime of the program is {end - begin} seconds")

bond_prices_df

In [1]:
import sympy as sp
x = sp.Symbol('x')
sp.solve( x**2 - 2, x)

[-sqrt(2), sqrt(2)]

In [2]:
import sympy as sp
x = sp.Symbol('x')
sp.solve( x**4 - x**2 - 1, x)

[-I*sqrt(-1/2 + sqrt(5)/2),
 I*sqrt(-1/2 + sqrt(5)/2),
 -sqrt(1/2 + sqrt(5)/2),
 sqrt(1/2 + sqrt(5)/2)]

In [3]:
import sympy as sp
x = sp.Symbol('x')
soln = sp.solve( x**4 - x**2 - 1, x)
for j in range(0, len(soln)):
    print(sp.N(soln[j]))

-0.786151377757423*I
0.786151377757423*I
-1.27201964951407
1.27201964951407


In [4]:
# Create a sample collection
users = {'Hans': 'active', 'Éléonore': 'inactive', '景太郎': 'active'}

# Strategy:  Iterate over a copy
for user, status in users.copy().items():
    if status == 'inactive':
        del users[user]

# Strategy:  Create a new collection
active_users = {}
for user, status in users.items():
    if status == 'active':
        active_users[user] = status

In [5]:
users

{'Hans': 'active', '景太郎': 'active'}

In [6]:
active_users

{'Hans': 'active', '景太郎': 'active'}

In [7]:
doubles = [2 * x for x in range(8)]
doubles

[0, 2, 4, 6, 8, 10, 12, 14]

In [9]:
doubles = [2 * x for x in range(8)]
doubles

TypeError: object of type 'int' has no len()

In [11]:
a = [e * 2 for e in range(8)]

In [12]:
a

[0, 2, 4, 6, 8, 10, 12, 14]

In [20]:
import numpy as np
maturity_years = 3
times = np.arange(0.5, (maturity_years + 0.5), 0.5)

In [21]:
times

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [22]:
times[:-1]

array([0.5, 1. , 1.5, 2. , 2.5])

In [25]:
    coupon = 3.5
    principal_payment = 100
    semi_annual_coupon = coupon / 2 
    cashflows = np.array([])
    for i in times[:-1]:
        # times[:-1] gives array([0.5, 1. , 1.5, 2. , 2.5]), here last element gets removed from array using -1
        #         cashflows = np.append(cashflows, annual_coupon) # For Annual Cashflows
        #     cashflows = np.append(cashflows, annual_coupon+principal_payment)#  For Annual Cashflows
        cashflows = np.append(
            cashflows, semi_annual_coupon
        )  # For Semi-Annual Cashflows
    cashflows = np.append(
        cashflows, semi_annual_coupon + principal_payment
    )  # For Semi-Annual Cashflows


In [26]:
cashflows

array([  1.75,   1.75,   1.75,   1.75,   1.75, 101.75])